### ISSUE TITLE
user feedback: condensed view

### ISSUE THREAD

**Issue by inklesspen** [enigmalea/Archivist#6]
A user on my server sent the following:

I'm not sure if you have any control over the bots display settings, but if so it might be worth messing w/ them to save space on mobile. In particular,  make the ratings images smaller (or switch to text instead of images) and get rid of the newlines between the label and the info. That is, 

> "**Chapters:** 8/8"

Instead of

> "**Chapters:**
> 8/8"

**Comment by enigmalea** [comment]
Thanks for reaching out! Unfortunately, that has to do with how Discord embeds work, in general.

Discord embeds have two ways to display text: descriptions and fields. 

![image](https://user-images.githubusercontent.com/73132777/187039543-bc42022a-8bbf-429b-9d33-4ddf0f62c189.png)
(*screenshot stolen from the discord.js guide and abused for this conversation*)

Descriptions only allow a string of text with line breaks. So if I throw everything into a description I can do:
**Chapters:** 8/8

But with fields you MUST have a title/name and a value, and Discord renders those on separate lines.

There's also character limitations.
- Embed descriptions are limited to 4096 characters
- There can be up to 25 fields
- A field's name is limited to 256 characters and its value to 1024 characters

With the variable nature of the things that go into descriptions (authors, series, and eventually collections), if I try to shove more in it there's a real possibility I could hit the maximum characters for an embed description and the embed would fail to send.

I also use fields, because they can be placed beside one another to save room on desktop. These 9 fields could take up a lot of room if I tried to shove them in a description, as that would be 9 more lines of text (or more)
![image](https://user-images.githubusercontent.com/73132777/187039875-cc879a73-4611-4993-8b6a-fa3f4e280e8d.png)

I do think I will be removing this AO3 logo here during the rewrite, and instead, if there are images in a work, having the first one rendered in the spot for larger images at the end of an embed, but that is pretty far away.
![image](https://user-images.githubusercontent.com/73132777/187040032-390785f0-6ca3-47b2-9c74-c71fffdac32b.png)

**Comment by enigmalea** [comment]
Closing this issue as it will be completed as part of the rewrite project found [here](https://github.com/users/enigmalea/projects/1). On completion this repo will be archived, as the Discord API it uses to function is being sunset during 2023, and the code will no longer be valid for use.
